---
settings:
  name: Google Cloud Storage
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de Google Cloud Storage
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Ver sus depósitos de Google Cloud Storage
      url: "/task-viewing-gcp-storage.html"
  - title: Administrar depósitos de Google Cloud Storage
    entries:
    - title: Agregar nuevos depósitos
      url: "/task-add-gcp-bucket.html"
    - title: Cambiar la configuración del depósito
      url: "/task-change-gcp-bucket-settings.html"
    - title: Utilice los servicios de datos de NetApp con los buckets de Google Cloud
        Storage
      url: "/task-gcp-enable-data-services.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
