---
sidebar: sidebar 
permalink: task-gcp-enable-data-services.html 
keywords: google buckets, google storage, google cloud storage working environment, google cloud storage buckets, system 
summary: Cuando descubres depósitos de Google Cloud Storage en la NetApp Console, puedes usar los servicios de datos de NetApp para realizar copias de seguridad, organizar en niveles y sincronizar datos. 
---
= Utilice los servicios de datos de NetApp con los buckets de Google Cloud Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando descubres depósitos de Google Cloud Storage en la NetApp Console, puedes usar los servicios de datos de NetApp para realizar copias de seguridad, organizar en niveles y sincronizar datos.

* Utilice * NetApp Backup and Recovery* para realizar copias de seguridad de los datos de sus sistemas ONTAP locales y Cloud Volumes ONTAP en el almacenamiento de objetos de Google Cloud.
+
Para comenzar, vaya a la página Sistemas y arrastre y suelte un sistema ONTAP local o Cloud Volumes ONTAP en su sistema Google Cloud Storage.

+
https://docs.netapp.com/us-en/data-services-backup-recovery/concept-ontap-backup-to-cloud.html["Obtenga más información sobre cómo realizar copias de seguridad de los datos de ONTAP en Google Cloud Storage"^] .

* Utilice * NetApp Cloud Tiering* para organizar en niveles los datos inactivos desde los clústeres ONTAP locales al almacenamiento de objetos de Google Cloud.
+
Para comenzar, vaya a la página Sistemas y arrastre y suelte un sistema ONTAP local en su sistema Google Cloud Storage.

+
https://docs.netapp.com/us-en/data-services-cloud-tiering/task-tiering-onprem-gcp.html["Obtenga más información sobre cómo organizar los datos de ONTAP en niveles en Google Cloud Storage"^] .

* Utilice * NetApp Copy and Sync* para sincronizar datos hacia o desde los depósitos de Google Cloud Storage.
+
Para comenzar, vaya a la página Sistemas y arrastre y suelte el sistema de origen en el sistema de destino. Su sistema de almacenamiento en la nube de Google puede ser el origen o el destino.



También puede seleccionar su sistema de Google Cloud Storage y hacer clic en *Copiar y sincronizar* en el panel Servicios para sincronizar datos hacia o desde los depósitos de Cloud Storage.

https://docs.netapp.com/us-en/data-services-copy-sync/concept-cloud-sync.html["Obtenga más información sobre el servicio de NetApp Copy and Sync"^] .
